NAME     : SAI MANOHAR VEMURI \
ID       : A20514848\
Course   : CS512\
SEMESTER : SPRING 23\
ASSIGNMENT 0

In [25]:
import numpy as np
a=np.array([1,2,3]).reshape(3,1)
b=np.array([4,5,6]).reshape(3,1)
c=np.array([-1,1,3]).reshape(3,1)

In [195]:
print('A=\n',a)
print('B=\n',b)
print('C=\n',c)


A=
 [[1]
 [2]
 [3]]
B=
 [[4]
 [5]
 [6]]
C=
 [[-1]
 [ 1]
 [ 3]]


# A-1

In [26]:
(2*a)-b

array([[-2],
       [-1],
       [ 0]])

# A-2

In [30]:
import math
def magnitude(x):
    return math.sqrt(sum(x**2))

a_mag=magnitude(a)
uv=a/a_mag
print(uv)

[[0.26726124]
 [0.53452248]
 [0.80178373]]


# A-3

In [43]:
bX=np.array([1,0,0]).reshape(3,1)
#bX is X axis
Cosθ=(a*bX)/(magnitude(a)*magnitude(bX))
invCosθ=math.degrees(np.arccos(0.26))
print(invCosθ)

74.92993785511118


# A-4

In [45]:
CosDirection_A=(a/magnitude(a))
print(CosDirection_A)

[[0.26726124]
 [0.53452248]
 [0.80178373]]


# A-5

In [88]:
Cosθ=sum(a*b)/(magnitude(a)*magnitude(b))
print(Cosθ)

[0.97463185]


# A-6

In [62]:
print('AxB:')
print(a*b)
print('\nBxA:')
print(b*a)
print('\nCommutative')

AxB:
[[ 4]
 [10]
 [18]]

BxA:
[[ 4]
 [10]
 [18]]

Commutative


# A-7

In [65]:
print(Cosθ*magnitude(a)*magnitude(b))

[32.]


# A-8

In [74]:
sum(a*b)/magnitude(a)

array([8.55235974])

# A-9

In [190]:
from sympy import symbols, Eq, solve
x1,x2,x3 = symbols('x1 x2 x3')
expr = x1+2*x2+3*x3
# set random values to x2 and x3. X2=4 and X3=5
expr=expr.subs({x2:4, x3: 5})
sol=solve(expr, dict=True)
print(sol)
# vector which is perpendicular to A:
perpVector=np.array([sol[0][x1],4,5]).reshape(3,1)
print('\nvector which is perpendicular to A is:')
print(perpVector)

[{x1: -23}]

vector which is perpendicular to A is:
[[-23]
 [4]
 [5]]


# A-10

In [201]:
print('a X b=',np.cross(a.reshape(1,3),b.reshape(1,3)))
print('b X a=',np.cross(b.reshape(1,3),a.reshape(1,3)))

a X b= [[-3  6 -3]]
b X a= [[ 3 -6  3]]


# A-11

In [202]:
print('a X b=',np.cross(a.reshape(1,3),b.reshape(1,3)))

a X b= [[-3  6 -3]]


# A-12

In [242]:

import math
X=np.array([a.reshape(1,3),b.reshape(1,3),c.reshape(1,3)])
X=np.matrix(X).transpose()
print(X)
y=np.array([0,0,0])
Z=np.linalg.det(X)
print(round(Z))
print("there exist a linear dependency in the columns of the matrix")
np.linalg.lstsq(X, y )



[[ 1  4 -1]
 [ 2  5  1]
 [ 3  6  3]]
0
there exist a linear dependency in the columns of the matrix


C:\Users\MANOHA~1\AppData\Local\Temp/ipykernel_14700/1634091664.py:9: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(X, y )


(array([0., 0., 0.]),
 array([], dtype=float64),
 2,
 array([9.78772464e+00, 2.49006956e+00, 2.15329741e-16]))

# A-13

In [243]:
a=np.matrix([1,2,3])
b=np.matrix([4,5,6])
print('AtB=',a.transpose()*b)


print('\nBtA=',a*b.transpose())

AtB= [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]

BtA= [[32]]


# B-1

In [282]:
A=np.matrix([[1,2,3],[4,-2,3],[0,5,-1]])
B=np.matrix([[1,2,1],[2,1,-4],[3,-2,1]])
C=np.matrix([[1,2,3],[4,5,6],[-1,1,3]])
print((2*A)-B)

[[ 1  2  5]
 [ 6 -5 10]
 [-3 12 -3]]


# B-2

In [248]:
print('A.B:\n',np.matmul(A,B))
print('B.A:\n',np.matmul(B,A))

A.B:
 [[ 14  -2  -4]
 [  9   0  15]
 [  7   7 -21]]
B.A:
 [[  9   3   8]
 [  6 -18  13]
 [ -5  15   2]]


# B-3

In [255]:
print('(A.B)T:\n',np.matmul(A,B).transpose())
print('\nAT.BT:\n',np.matmul(B.transpose(),A.transpose()))

(A.B)T:
 [[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]

AT.BT:
 [[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]


# B-4

In [259]:
print('|A|:',np.linalg.det(A))
print('|C|',np.linalg.det(C))

|A|: 54.999999999999964
|C| 7.494005416219837e-16


# B-5

In [ ]:
x=np.matrix([[1,0,0],[0,0,0],[0,0,0]])
print(" for A")
print(A.transpose()*A)
print("for B")
print(B.transpose()*B)
print("for C")
print(C.transpose()*C)

# B-6

In [262]:
print("A inverse:\n",np.linalg.inv(A))
print()
print("B inverse:\n",np.linalg.inv(B))

A inverse:
 [[-0.23636364  0.30909091  0.21818182]
 [ 0.07272727 -0.01818182  0.16363636]
 [ 0.36363636 -0.09090909 -0.18181818]]

B inverse:
 [[ 0.16666667  0.0952381   0.21428571]
 [ 0.33333333  0.04761905 -0.14285714]
 [ 0.16666667 -0.19047619  0.07142857]]


# B-7

In [263]:
print('Since determinant is 0, it is non invertible')

Since determinant is 0, it is non invertible


# B-8

In [264]:
print(np.matmul(A,np.matrix([[1,2,3]]).transpose()))

[[14]
 [ 9]
 [ 7]]


# B-9

In [287]:
A=np.array([[1,2,3],[4,-2,3],[0,5,-1]])
d=np.array([1,2,3])
for i in range(len(A)):
    print(sum(A[i]*d)/magnitude(d))

3.7416573867739413
2.4053511772118195
1.8708286933869707


# B-10

In [294]:
for i in range(len(A)):
    AXD=sum(A[i]*d)
    mag=magnitude(d)**2
    vecPro=AXD/mag
    print(vecPro*d)

[1. 2. 3.]
[0.64285714 1.28571429 1.92857143]
[0.5 1.  1.5]


# B-11

In [295]:
d1=d[0]*A.transpose()[0]
d2=d[1]*A.transpose()[1]
d3=d[2]*A.transpose()[2]
print(d1+d2+d3)

[14  9  7]


# B-12

In [296]:
print(np.linalg.solve(B, d))

[ 1.00000000e+00  2.37904934e-17 -1.18952467e-17]


# B-13

In [298]:
print(np.linalg.solve(C, d))
print('There is no solution')

[-8.00639934e+15  1.60127987e+16 -8.00639934e+15]
There is no solution


# C-1

In [307]:
from numpy.linalg import eig
D=np.array([[1,2],[3,2]])
print(D)
val,vec=eig(D)
print('Eigen value:\n',val)
print('Eigen Vector\n',vec)

[[1 2]
 [3 2]]
Eigen value:
 [-1.  4.]
Eigen Vector
 [[-0.70710678 -0.5547002 ]
 [ 0.70710678 -0.83205029]]


# C-2

In [303]:
vec1=np.array([-0.70710678,-0.5547002])
vec2=np.array([0.70710678,-0.83205029])
print(np.dot(vec1,vec2))

-0.038461536048910505


# C-3

In [306]:
E=np.array([[2,-2],[-2,5]])
val,vec=eig(E)
print('Eigen value:\n',val)
print('Eigen Vector\n',vec)

Eigen value:
 [1. 6.]
Eigen Vector
 [[-0.89442719  0.4472136 ]
 [-0.4472136  -0.89442719]]


# C-4

In [308]:
vec1=np.array([-0.89442719,0.4472136])
vec2=np.array([-0.4472136,-0.89442719])
print(np.dot(vec1,vec2))
print("The matrix is symmetrical and positive definite matrix where every eigen value is positive")

0.0
The matrix is symmetrical and positive definite matrix where every eigen value is positive


# C-5

In [311]:
F=np.array([[1,2],[2,4]])
d=np.array([0,0])
print(np.linalg.solve(F, d))

LinAlgError: Singular matrix

# C-7

In [314]:
D=np.array([[1,2],[3,2]])
d=np.array([0,0])
print(np.linalg.solve(D, d))

[0. 0.]
